### PR TITLE
Add commented env file example

### PR DESCRIPTION
**Pull request by robertodauria**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/autonode/10)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/10)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`examples/env` line 7 at r1](https://reviewable.io/reviews/m-lab/autonode/10#-O5Ji4cW8xzSmdlMwF1D:-O5Ji4cW8xzSmdlMwF1E:bxxzhgr) ([raw file](https://github.com/m-lab/autonode/blob/5eb8f924bb34f3bf25e1a377d135fff1f18cd435/examples/env#L7)):*
> ```
> # In addition to this, you will need a service account key file (provided by
> # M-Lab). This service account key is expected to be placed, relative to the
> # ndt-fullstack YAML file's path, in certs/service-account-autojoin.json
> ```

Please mention the `html` directory also. I suggest making this section about "external directories" and listing each with a description like you have here for `./certs`.
___
*[`examples/env` line 15 at r1](https://reviewable.io/reviews/m-lab/autonode/10#-O5JgfV39UxcPzHYohgP:-O5JgfV39UxcPzHYohgQ:b-gspi47) ([raw file](https://github.com/m-lab/autonode/blob/5eb8f924bb34f3bf25e1a377d135fff1f18cd435/examples/env#L15)):*
> ```
> API_KEY=
> 
> # IATA is the IATA code of the nearest international airport.
> ```

Clarify that this is three letters. Include a link to the autojoin Lookup resource:
https://autojoin-dot-mlab-autojoin.appspot.com/autojoin/v0/lookup[?lat=<lat>&lon=<lon>]

(Which makes me think we should create a permanent URL like autojoin.measurementlab.net too)
___
*[`examples/env` line 28 at r1](https://reviewable.io/reviews/m-lab/autonode/10#-O5JgKeR25BBsmzJyCA0:-O5JgKeR25BBsmzJyCA1:b-pzdkb3) ([raw file](https://github.com/m-lab/autonode/blob/5eb8f924bb34f3bf25e1a377d135fff1f18cd435/examples/env#L28)):*
> ```
> 
> # INTERFACE_MAXRATE is the rate (in bit/s) after which the NDT server will
> # refuse new connections. Set it according to this node's uplink.
> ```

I recommend adding suggested settings, e.g. for 1Gbps uplink use 150000000, for 10Gbps use 7000000000.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/10)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`examples/env` line 7 at r1](https://reviewable.io/reviews/m-lab/autonode/10#-O5Ji4cW8xzSmdlMwF1D:-O5P0_4rCODKgBmJQKCJ:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/5eb8f924bb34f3bf25e1a377d135fff1f18cd435/examples/env#L7)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please mention the `html` directory also. I suggest making this section about "external directories" and listing each with a description like you have here for `./certs`.
</blockquote></details>

Done.
___
*[`examples/env` line 15 at r1](https://reviewable.io/reviews/m-lab/autonode/10#-O5JgfV39UxcPzHYohgP:-O5P0_mwAmS7LpKk5hQg:b-b8jfja) ([raw file](https://github.com/m-lab/autonode/blob/5eb8f924bb34f3bf25e1a377d135fff1f18cd435/examples/env#L15)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Clarify that this is three letters. Include a link to the autojoin Lookup resource:
https://autojoin-dot-mlab-autojoin.appspot.com/autojoin/v0/lookup[?lat=<lat>&lon=<lon>]

(Which makes me think we should create a permanent URL like autojoin.measurementlab.net too)
</blockquote></details>

Done. (noting that the lookup gives weird results for `(0,0)` )
___
*[`examples/env` line 28 at r1](https://reviewable.io/reviews/m-lab/autonode/10#-O5JgKeR25BBsmzJyCA0:-O5P0fdJEpLd1SQbdwKA:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/5eb8f924bb34f3bf25e1a377d135fff1f18cd435/examples/env#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend adding suggested settings, e.g. for 1Gbps uplink use 150000000, for 10Gbps use 7000000000.
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
One more suggestion for the dirs documentation.

:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/10#-:-O5P3fmH56nGr3S9fA04:b6mxk4)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

___
*[`examples/env` line 7 at r1](https://reviewable.io/reviews/m-lab/autonode/10#-O5Ji4cW8xzSmdlMwF1D:-O5P31fXASyLCaTRbyp5:b-8l1w3j) ([raw file](https://github.com/m-lab/autonode/blob/5eb8f924bb34f3bf25e1a377d135fff1f18cd435/examples/env#L7)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you!

What permissions should these files have? Who creates them? 

(Do we actually need all of them to be present in the local directory? Does docker-compose have a notion like k8s for `emptyDir` volume types? Would that work for any of these dirs?)

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/10)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

___
*[`examples/env` line 7 at r1](https://reviewable.io/reviews/m-lab/autonode/10#-O5Ji4cW8xzSmdlMwF1D:-O5PPVg0-fROcUH7eIsP:b-ruyojq) ([raw file](https://github.com/m-lab/autonode/blob/5eb8f924bb34f3bf25e1a377d135fff1f18cd435/examples/env#L7)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you!

What permissions should these files have? Who creates them? 

(Do we actually need all of them to be present in the local directory? Does docker-compose have a notion like k8s for `emptyDir` volume types? Would that work for any of these dirs?)
</blockquote></details>

All the folders are created by Docker the first time a container that mounts them as volumes start. The owner will be the same user Docker runs under. This generally means root. [Rootless Docker](https://docs.docker.com/engine/security/rootless/) is still a somewhat fringe configuration that requires extra tools to be installed, apparmor profiles, etc.

I added a note about who creates the folders. None of them except for `certs` (or `html`, if they want to provide their own UI) should be created by the user.

**Pull request merged**
