### PR TITLE
Add fullstack NDT node example

### PR DESCRIPTION
**Pull request by robertodauria**
This adds an example docker-compose to run fullstack NDT and make it part of the M-Lab platform. It expects variables to be provided via either the command line or a `.env` file. Example:

```
API_KEY=<key provided by M-Lab>
ORGANIZATION=<org name>
PROJECT=mlab-autojoin
IATA=<IATA code, lowercase>
LOCATE_URL=locate.measurementlab.net
```

This change is [Reviewable](https://reviewable.io/reviews/m-lab/autonode/3)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/3)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`examples/ndt-fullstack.yml` line 4 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SwOhL9mB5nwfenZ1Z:-O1SwOhL9mB5nwfenZ1_:bxajxf7) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L4)):*
> ```YAML
> services:
>   register-node:
>     image: measurementlab/autojoin-register:oneshot
> ```

Do I understand correctly that once the DNS GC is running oneshot deployments will start to fail?

What would we need to do to enable a service version deployment using the "service_healthy" condition?
___
*[`examples/ndt-fullstack.yml` line 82 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1Sx2KP9375ZRux4qLl:-O1Sx2KP9375ZRux4qLm:b3xcw34) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L82)):*
> ```YAML
>       - -label=managed=none
>       # TODO: add helpful server location metadata labels.
>       - -label=region=TODO
> ```

Is this needed any more? Or what would be a better value?
___
*[`examples/ndt-fullstack.yml` line 107 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SyDzp4waK6RAcrwy1:-O1SyDzp4waK6RAcrwy2:b-lrhm9z) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L107)):*
> ```YAML
> 
>   uuid-annotator:
>     image: measurementlab/uuid-annotator:latest
> ```

is there a tagged version now?
___
*[`examples/ndt-fullstack.yml` line 119 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SydqwAbAu_b1k76PE:-O1SydqwAbAu_b1k76PF:bdt938d) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L119)):*
> ```YAML
>     network_mode: "service:ndt-server"
>     environment:
>       # TODO: reference service account credentials for upload to GCS.
> ```

Is TODO obsolete?
___
*[`examples/ndt-fullstack.yml` line 121 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SyfJ26RnzoxPQrYvN:-O1SyfJ26RnzoxPQrYvO:b-6e0gqn) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L121)):*
> ```YAML
>       # TODO: reference service account credentials for upload to GCS.
>       - GOOGLE_APPLICATION_CREDENTIALS=/certs/service-account-autojoin.json
>     # NOTE: all database URLs are required. Minimal, incomplete versions of
> ```

I suggest you remove everything after the first sentence from "Minimal.*"
___
*[`examples/ndt-fullstack.yml` line 135 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1Syt6o0VCm6AJAlylS:-O1Syt6o0VCm6AJAlylT:bakwzca) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L135)):*
> ```YAML
> 
>   jostler:
>     # TODO: replace tag once changes are merged
> ```

Looks obsolete
___
*[`examples/ndt-fullstack.yml` line 157 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SyrUp4T6V7e07UwUA:-O1SyrUp4T6V7e07UwUB:bakwzca) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L157)):*
> ```YAML
>       - -gcs-data-dir=autoload/v2
>       - -local-data-dir=/resultsdir
>       # TODO: update organization name.
> ```

Looks obsolete

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/3)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`examples/ndt-fullstack.yml` line 4 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SwOhL9mB5nwfenZ1Z:-O1Szj6o-WmrHAtWelSP:btbfmk9) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do I understand correctly that once the DNS GC is running oneshot deployments will start to fail?

What would we need to do to enable a service version deployment using the "service_healthy" condition?
</blockquote></details>

Yes, the oneshot register client does not periodically renew the registration, so the DNS GC would eventually remove the entry for that client.

IIUC, service_healthy is based on a healthcheck that must be defined for the register-node service. It can be any command, for example we could test for the existence of the expected files (annotation.json, registration.json, hostname) or curl an endpoint of the autojoin-register service that returns the status of the last registration.
___
*[`examples/ndt-fullstack.yml` line 82 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1Sx2KP9375ZRux4qLl:-O1T-UZb1-h8boDU5FXE:b-no8uzm) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L82)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this needed any more? Or what would be a better value?
</blockquote></details>

Some of these TODO are meant for the user, to signal places where they are expected to change the values according to their environment. How would you recommend to change it to make it clearer?
___
*[`examples/ndt-fullstack.yml` line 107 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SyDzp4waK6RAcrwy1:-O1T-e2HBi9RO7xpmsWm:b1nbd49) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L107)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

is there a tagged version now?
</blockquote></details>

Yup, now there is. I'll update it.
___
*[`examples/ndt-fullstack.yml` line 119 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SydqwAbAu_b1k76PE:-O1T0UnY7bgJgSO7PPL1:blg84dw) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L119)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is TODO obsolete?
</blockquote></details>

Same as above, the idea (until we move to a model where the registration endpoint provides this service account file) is that the user puts the .json file we provide under certs and updates this variable accordingly. This may be also be a no-op, depending on how we instruct them.
___
*[`examples/ndt-fullstack.yml` line 121 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SyfJ26RnzoxPQrYvN:-O1T1KQK4noQaVDb4Dtf:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L121)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest you remove everything after the first sentence from "Minimal.*"
</blockquote></details>

Done.
___
*[`examples/ndt-fullstack.yml` line 135 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1Syt6o0VCm6AJAlylS:-O1T19uPEV3-GlbWifmN:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L135)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Looks obsolete
</blockquote></details>

Done.
___
*[`examples/ndt-fullstack.yml` line 157 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SyrUp4T6V7e07UwUA:-O1T1JRAB-lYRqKz--gK:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L157)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Looks obsolete
</blockquote></details>

Done.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/3)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`examples/ndt-fullstack.yml` line 4 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SwOhL9mB5nwfenZ1Z:-O1T2PwP4e9xeYJK5rJ3:b-fgozjc) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L4)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Yes, the oneshot register client does not periodically renew the registration, so the DNS GC would eventually remove the entry for that client.

IIUC, service_healthy is based on a healthcheck that must be defined for the register-node service. It can be any command, for example we could test for the existence of the expected files (annotation.json, registration.json, hostname) or curl an endpoint of the autojoin-register service that returns the status of the last registration.
</blockquote></details>

What would happen if we deployed RNP to production with the oneshot before the DNS GC is deployed in production?
___
*[`examples/ndt-fullstack.yml` line 82 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1Sx2KP9375ZRux4qLl:-O1T35vVCaI6b3J5DqOq:b-y7p5v6) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L82)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Some of these TODO are meant for the user, to signal places where they are expected to change the values according to their environment. How would you recommend to change it to make it clearer?
</blockquote></details>

Oh, I see - how about `TODO(host)` and `TODO(mlab)`?

For RNP I may have been thinking of their federal districts, something that's meaningful to them and helpful for users of the data. Maybe comment this label out so it's not included unless explicitly added.
___
*[`examples/ndt-fullstack.yml` line 119 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SydqwAbAu_b1k76PE:-O1T2hxC-6X3N4pJNZqm:b-ub20vn) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L119)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Same as above, the idea (until we move to a model where the registration endpoint provides this service account file) is that the user puts the .json file we provide under certs and updates this variable accordingly. This may be also be a no-op, depending on how we instruct them.
</blockquote></details>

Ultimately this service account will be issued via the Register API and written to disk.

Maybe update the `TODO(mlab): replace service account with output from the output of register`? (or similar)
___
*[`examples/ndt-fullstack.yml` line 147 at r3](https://reviewable.io/reviews/m-lab/autonode/3#-O1T3e9-0Av45QDRnJFF:-O1T3e90CPoL6qxgAcsk:b-2guby3) ([raw file](https://github.com/m-lab/autonode/blob/6477cca5508c7ff68bda80fa0b00eda39e150457/examples/ndt-fullstack.yml#L147)):*
> ```YAML
>         condition: service_completed_successfully
>     environment:
>       # TODO: reference service account credentials for upload to GCS.
> ```

same here

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/3)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`examples/ndt-fullstack.yml` line 4 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SwOhL9mB5nwfenZ1Z:-O1T47jS0sYb2-lBNluF:bj30stk) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What would happen if we deployed RNP to production with the oneshot before the DNS GC is deployed in production?
</blockquote></details>

The autojoin API will create DNS entries that aren't tracked in memorystore nor subject to any expiration. Once we deploy the DNS GC, it'll start tracking the RNP hostnames only after the next call to /register (i.e. when this docker-compose is restarted). It's fundamental that we coordinate the deployment of the DNS GC with the replacement of the "oneshot" client with the service, to ensure that registrations are periodically refreshed.
___
*[`examples/ndt-fullstack.yml` line 82 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1Sx2KP9375ZRux4qLl:-O1T59zE7lNC4gFs-axt:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L82)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oh, I see - how about `TODO(host)` and `TODO(mlab)`?

For RNP I may have been thinking of their federal districts, something that's meaningful to them and helpful for users of the data. Maybe comment this label out so it's not included unless explicitly added.
</blockquote></details>

Done.
___
*[`examples/ndt-fullstack.yml` line 119 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SydqwAbAu_b1k76PE:-O1T5MvF0Eua_y2-HeG7:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L119)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ultimately this service account will be issued via the Register API and written to disk.

Maybe update the `TODO(mlab): replace service account with output from the output of register`? (or similar)
</blockquote></details>

Done.
___
*[`examples/ndt-fullstack.yml` line 147 at r3](https://reviewable.io/reviews/m-lab/autonode/3#-O1T3e9-0Av45QDRnJFF:-O1T5XI854UjLHdlSgyx:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/6477cca5508c7ff68bda80fa0b00eda39e150457/examples/ndt-fullstack.yml#L147)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Review by stephen-soltesz — COMMENTED** [review]
A few more quick comments/questions - we don't want them to use the production configuration until we know the server annotations are correct right? How will we ensure that?

> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/3#-:-O1T6zWW-z1tgE3tFCBS:b4vhoej)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`examples/ndt-fullstack.yml` line 4 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SwOhL9mB5nwfenZ1Z:-O1T6_Ei9WDPPLoiQGak:bxvomee) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L4)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

The autojoin API will create DNS entries that aren't tracked in memorystore nor subject to any expiration. Once we deploy the DNS GC, it'll start tracking the RNP hostnames only after the next call to /register (i.e. when this docker-compose is restarted). It's fundamental that we coordinate the deployment of the DNS GC with the replacement of the "oneshot" client with the service, to ensure that registrations are periodically refreshed.
</blockquote></details>

Ah - there will be no TTL on old names until the next registration - that's the piece I was missing. I was worried they would be erased right away. When DNS GC goes live we'll want a replacement to give them at the same time so a restart of the oneshot doesn't take them out of service.
___
*[`examples/ndt-fullstack.yml` line 73 at r4](https://reviewable.io/reviews/m-lab/autonode/3#-O1T6V_tE-Y2VEhwGb3Y:-O1T6V_tE-Y2VEhwGb3Z:b-mhh87f) ([raw file](https://github.com/m-lab/autonode/blob/baa3a65cd84fba9fb387fb0d9335a3a638736b7c/examples/ndt-fullstack.yml#L73)):*
> ```YAML
>       # Allow ndt7 data to be autoloaded.
>       - -compress-results=false
>       # TODO: confirm device name.
> ```

What's the best way to label this TODO?
___
*[`examples/ndt-fullstack.yml` line 152 at r4](https://reviewable.io/reviews/m-lab/autonode/3#-O1T77jgBMvVgW4-N1_o:-O1T77jgBMvVgW4-N1_p:b-49w4om) ([raw file](https://github.com/m-lab/autonode/blob/baa3a65cd84fba9fb387fb0d9335a3a638736b7c/examples/ndt-fullstack.yml#L152)):*
> ```YAML
>       - -mlab-node-name-file=/autonode/hostname
>       # NOTE: the ndt7 schema must already exist in the target bucket.
>       - -gcs-bucket=archive-mlab-autojoin
> ```

Should this use the `${PROJECT}` variable?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/3)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`examples/ndt-fullstack.yml` line 4 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SwOhL9mB5nwfenZ1Z:-O1T9nYPBEtpYFhSXi4a:bdmi0n6) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ah - there will be no TTL on old names until the next registration - that's the piece I was missing. I was worried they would be erased right away. When DNS GC goes live we'll want a replacement to give them at the same time so a restart of the oneshot doesn't take them out of service.
</blockquote></details>

Correct - basically, as long as the DNS entry is not known by the GC it won't be touched. Once this docker-compose is restarted it'll become "known" and subject to expiration.
___
*[`examples/ndt-fullstack.yml` line 73 at r4](https://reviewable.io/reviews/m-lab/autonode/3#-O1T6V_tE-Y2VEhwGb3Y:-O1TA38N5y5ogI_9DP9U:bvbt918) ([raw file](https://github.com/m-lab/autonode/blob/baa3a65cd84fba9fb387fb0d9335a3a638736b7c/examples/ndt-fullstack.yml#L73)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What's the best way to label this TODO?
</blockquote></details>

Done (host).
___
*[`examples/ndt-fullstack.yml` line 152 at r4](https://reviewable.io/reviews/m-lab/autonode/3#-O1T77jgBMvVgW4-N1_o:-O1TA61F4RIf68ZTjYiJ:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/baa3a65cd84fba9fb387fb0d9335a3a638736b7c/examples/ndt-fullstack.yml#L152)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should this use the `${PROJECT}` variable?
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
We don't want them to use the production configuration until we know the server annotations are correct right? How will we ensure that?

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/3#-:-O1TAi2HE724vJc8Ng6b:b-far1z3)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

___
*[`examples/ndt-fullstack.yml` line 4 at r2](https://reviewable.io/reviews/m-lab/autonode/3#-O1SwOhL9mB5nwfenZ1Z:-O1TAU-n5v39crELQHnf:b708w9n) ([raw file](https://github.com/m-lab/autonode/blob/bd0fe283a78b3fb643e34db8a1856b3b46a64276/examples/ndt-fullstack.yml#L4)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Correct - basically, as long as the DNS entry is not known by the GC it won't be touched. Once this docker-compose is restarted it'll become "known" and subject to expiration.
</blockquote></details>

Please add a `NOTE` here - in case we're not the ones responding

**Pull request merged**
