### PR TITLE
Add cloudbuild deployment script

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds a deployment script to configure and start the ndt-fullstack docker compose in the autonode VM (https://github.com/m-lab/terraform-support/pull/85).

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/autonode/7)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/7)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`deploy.sh` line 10 at r1](https://reviewable.io/reviews/m-lab/autonode/7#-O4go8gVDbMsDEwtwGmi:-O4go8gVDbMsDEwtwGmj:b-ja5hml) ([raw file](https://github.com/m-lab/autonode/blob/8bf2e42723a64b02487d9dbb43e0e5d65a60a6cb/deploy.sh#L10)):*
> ```Shell
> API_KEY=${4:?Please provide the API key: ${USAGE}}
> 
> VM_ZONE="us-central1-a"
> ```

nit: there is an inconsistency between accepting an IATA parameter and hard coding the zone. I suggest hard coding the iata also.
___
*[`deploy.sh` line 15 at r1](https://reviewable.io/reviews/m-lab/autonode/7#-O4goLpG7hIoB9hnX3R4:-O4goLpG7hIoB9hnX3R5:bmyqg42) ([raw file](https://github.com/m-lab/autonode/blob/8bf2e42723a64b02487d9dbb43e0e5d65a60a6cb/deploy.sh#L15)):*
> ```Shell
> LOCATE_URL="locate-dot-${PROJECT}.appspot.com"
> PROBABILITY="1.0"
> INTERFACE_NAME="eth0"
> ```

Just confirming, this is the correct interface name?

Also should this variable be used in the ssh script? (similarly with maxrate)
___
*[`deploy.sh` line 30 at r1](https://reviewable.io/reviews/m-lab/autonode/7#-O4gpAqC6AZybF7SvFmu:-O4gpAqC6AZybF7SvFmv:b3xsdxw) ([raw file](https://github.com/m-lab/autonode/blob/8bf2e42723a64b02487d9dbb43e0e5d65a60a6cb/deploy.sh#L30)):*
> ```Shell
>     cut -f1 -d " " | tail -n +2)
> do
>     gcloud iam service-accounts keys delete --iam-account=${SA_ACCOUNT} ${key} -q || true
> ```

note: this might make concurrent deployments fail in unexpected ways e.g. from two merged prs
___
*[`examples/ndt-fullstack.yml` line 37 at r1](https://reviewable.io/reviews/m-lab/autonode/7#-O4grE6z8GI2tH_bEhJW:-O4grE6z8GI2tH_bEhJX:bo2w83b) ([raw file](https://github.com/m-lab/autonode/blob/7e9a83183ffb0e175a48a608ba79847f74eb7c7b/examples/ndt-fullstack.yml#L37)):*
> ```YAML
>       - ALL
>     cap_add:
>       - NET_BIND_SERVICE
> ```

I thought I understood your explanation for removing 'cap_drop' -- I didn't expect removing NET_BIND_SERVICE - this is unnecessary b/c docker runs as root? We've seen environments where this is not universally true - for example, assumptions I had about how we ran pusher and tried to offer that to Kevin for revtr exports and it didn't work b/c his docker daemon ran differently. I'm not sure what the right configuration is I'm just noting that we may not always be able to assume "root will take care of it".

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/7)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`deploy.sh` line 15 at r1](https://reviewable.io/reviews/m-lab/autonode/7#-O4goLpG7hIoB9hnX3R4:-O4jtwq-BPAzLxfmdtT7:b-896fix) ([raw file](https://github.com/m-lab/autonode/blob/8bf2e42723a64b02487d9dbb43e0e5d65a60a6cb/deploy.sh#L15)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just confirming, this is the correct interface name?

Also should this variable be used in the ssh script? (similarly with maxrate)
</blockquote></details>

Done.
___
*[`deploy.sh` line 30 at r1](https://reviewable.io/reviews/m-lab/autonode/7#-O4gpAqC6AZybF7SvFmu:-O4jtxir9N7eCcXCNhrq:b3szf76) ([raw file](https://github.com/m-lab/autonode/blob/8bf2e42723a64b02487d9dbb43e0e5d65a60a6cb/deploy.sh#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

note: this might make concurrent deployments fail in unexpected ways e.g. from two merged prs
</blockquote></details>

Agreed - not sure how to make sure it doesn't happen, though. Perhaps filtering the output of `gcloud iam service accounts` for keys that were created more than X minutes ago?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/7)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`deploy.sh` line 30 at r1](https://reviewable.io/reviews/m-lab/autonode/7#-O4gpAqC6AZybF7SvFmu:-O4jwQM09oh_vGMNJJGk:b-kjcj7w) ([raw file](https://github.com/m-lab/autonode/blob/8bf2e42723a64b02487d9dbb43e0e5d65a60a6cb/deploy.sh#L30)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Agreed - not sure how to make sure it doesn't happen, though. Perhaps filtering the output of `gcloud iam service accounts` for keys that were created more than X minutes ago?
</blockquote></details>

I implemented this solution with X=10. Thoughts?

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/autonode/7#-:-O4k790mB6VVhqYB5xpx:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[`deploy.sh` line 30 at r1](https://reviewable.io/reviews/m-lab/autonode/7#-O4gpAqC6AZybF7SvFmu:-O4k6tEO3C64wnr8j3pL:bb7ohn6) ([raw file](https://github.com/m-lab/autonode/blob/8bf2e42723a64b02487d9dbb43e0e5d65a60a6cb/deploy.sh#L30)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I implemented this solution with X=10. Thoughts?
</blockquote></details>

sgtm

**Pull request merged**
